### PR TITLE
Bugfix -- I had used python-style ranges in the computePM function, now fixed to use JS syntax

### PR DESCRIPTION
**Pull request by bennywij**

### CODE REVIEW

**Comment by jasonsnell** [comment]
So the funny thing @bennywij is that I migrated this code to my Python script I run at home and didn't even realize it was broken on JS...

**Comment by bennywij** [comment]
Yep -- I wrote the python first to update my Swiftbar widget -- https://github.com/bennywij/junk-drawer/blob/master/purpleair-aqi.py#L46-L59 -- the same pm25 adjustment function we all re-wrote multiple times!

**Comment by jasonsnell** [comment]
LOL, I have a Swiftbar widget but it's mixed in with my current temp + Apple Weather widget. I actually ended up building a cron job on my server that pulls the PA JSON file every 15? minutes, parses it there, and outputs a bunch of stuff used by other scripts, rather than having them all hit PurpleAir at once...

**Comment by jasonsnell** [comment]
image

**Comment by bennywij** [comment]
Very cool. I love how free we “civilians” are to make stuff like that on the Mac, and wish the same will one day be true on iOS.

**Pull request merged**
